
apiVersion: eventing.triggermesh.io/v1alpha1
kind: RedisBroker
metadata:
  labels:
    triggermesh.io/context: triggermesh
  name: triggermesh

---

apiVersion: sources.triggermesh.io/v1alpha1
kind: KafkaSource
metadata:
  name: kafka-source
spec:
  groupID: mygroup
  bootstrapServers:
    - one-node-cluster-0.one-node-cluster.panda-pipes.svc.cluster.local.:9092
  topic: source-topic
  sink:
    ref:
      apiVersion: eventing.triggermesh.io/v1alpha1
      kind: RedisBroker
      name: triggermesh

---

apiVersion: targets.triggermesh.io/v1alpha1
kind: KafkaTarget
metadata:
  name: kafka-target
spec:
  bootstrapServers:
  - one-node-cluster-0.one-node-cluster.panda-pipes.svc.cluster.local.:9092
  topic: target-topic

---

apiVersion: eventing.triggermesh.io/v1alpha1
kind: Trigger
metadata:
  labels:
    triggermesh.io/context: triggermesh
  name: broker-to-kafka
spec:
  filters:
  - exact:
      type: transformed.event
  broker:
    group: eventing.triggermesh.io
    kind: RedisBroker
    name: triggermesh
  target:
    ref:
      apiVersion: targets.triggermesh.io/v1alpha1
      kind: KafkaTarget
      name: kafka-target

---

apiVersion: flow.triggermesh.io/v1alpha1
kind: Transformation
metadata:
  name: triggermesh-transformation
spec:
  context:
  - operation: add
    paths:
    - key: type
      value: transformed.event
  data:
  - operation: add
    paths:
    - key: new
      value: message

---

apiVersion: eventing.triggermesh.io/v1alpha1
kind: Trigger
metadata:
  labels:
    triggermesh.io/context: triggermesh
  name: broker-to-transformation
spec:
  filters:
  - exact:
      type: io.triggermesh.kafka.event
  broker:
    group: eventing.triggermesh.io
    kind: RedisBroker
    name: triggermesh
  target:
    ref:
      apiVersion: flow.triggermesh.io/v1alpha1
      kind: Transformation
      name: triggermesh-transformation